apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helm-guestbook
  template:
    metadata:
      labels:
        app: helm-guestbook
    spec:
      containers:
        - name: my-container
          image: nginx
