apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
  labels:
    app: helm-guestbook
    release: helm-guestbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helm-guestbook
  template:
    metadata:
      labels:
        app: helm-guestbook
    spec:
      containers:
        - name: my-container-gb
          image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        - name: my-container
          image: nginx
